Помогает одновременно вызывать и обрабатывать несколько несвязанных исключений. [^1]

Информация взята из [PEP 654](https://peps.python.org/pep-0654/)

[^1]: [Exception groups](https://docs.python.org/3/library/exceptions.html#lib-exception-groups)